# Generated by Django 4.2.5 on 2023-10-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidosexames',
            options={'verbose_name': 'Pedido Exame', 'verbose_name_plural': 'Pedidos Exames'},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoexame',
            options={'verbose_name': 'Solicitação Exame', 'verbose_name_plural': 'Solicitações Exames'},
        ),
        migrations.AlterModelOptions(
            name='tiposexames',
            options={'verbose_name': 'Tipo Exame', 'verbose_name_plural': 'Tipos Exames'},
        ),
    ]
